name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      native: ${{ steps.filter.outputs.native }}
      web: ${{ steps.filter.outputs.web }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Detect changes by filters
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            native:
              - './native/**'
            web:
              - './web/**'

  native:
    needs: changes
    if: ${{ needs.changes.outputs.native == 'true' }}
    env:
      WORKING_DIRECTORY: native
      BUILD_DIRECTORY: build
      BUILD_TYPE: Release
      EXECUTABLE_NAME: App
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        working-directory: ${{env.WORKING_DIRECTORY}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Checkout git submodules
        run: git submodule update --init --recursive

      # Install CMake
      - name: Install CMake (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y cmake
      - name: Install CMake (MacOS)
        if: runner.os == 'MacOs'
        run: brew install cmake
      - name: Install CMake (Windows)
        if: runner.os == 'Windows'
        run: choco install cmake
      - name: CMake Version
        run: cmake --version

      # Install dependencies
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y xorg-dev

      # Build
      - name: Configure CMake
        run: cmake -S . -B ${{env.BUILD_DIRECTORY}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{env.BUILD_DIRECTORY}} --config ${{env.BUILD_TYPE}}

      # Upload executable artifacts
      - name: Upload executable artifact (non-Windows)
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: webgpu-${{runner.os}}
          path: ${{env.WORKING_DIRECTORY}}/${{env.BUILD_DIRECTORY}}/${{env.EXECUTABLE_NAME}}
      - name: Upload executable artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: webgpu-${{runner.os}}
          path: ${{env.WORKING_DIRECTORY}}/${{env.BUILD_DIRECTORY}}/Release/${{env.EXECUTABLE_NAME}}.exe

  web:
    needs: changes
    if: ${{ needs.changes.outputs.web == 'true' }}
    env:
      WORKING_DIRECTORY: web
      BUILD_DIRECTORY: out
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.WORKING_DIRECTORY}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
      - name: Bun version
        run: bun --version
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Test (lint)
        run: bun run test:lint
      - name: Test (format)
        run: bun run test:format
      - name: Build
        run: bun run build
      - name: Upload static output artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: ${{env.WORKING_DIRECTORY}}/${{env.BUILD_DIRECTORY}}
