name: Native

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_DIRECTORY: build
  BUILD_TYPE: Release
  EXECUTABLE_NAME: App

jobs:
  native:
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        working-directory: ./native
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Checkout git submodules
        run: git submodule update --init --recursive
      # Install CMake
      - name: Install CMake (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y cmake
      - name: Install CMake (MacOS)
        if: runner.os == 'MacOs'
        run: brew install cmake
      - name: Install CMake (Windows)
        if: runner.os == 'Windows'
        run: choco install cmake
      - name: CMake Version
        run: cmake --version
      # Install dependencies
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y xorg-dev
      # Build
      - name: Generate CMake build files
        run: cmake -S . -B ${{env.BUILD_DIRECTORY}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build executable
        run: cmake --build ${{env.BUILD_DIRECTORY}} --config ${{env.BUILD_TYPE}}
      # Run
      - name: Run (non-Windows)
        if: runner.os != 'Windows'
        run: ./build/${{env.EXECUTABLE_NAME}}
      - name: Run (Windows)
        if: runner.os == 'Windows'
        run: .\build\${{env.BUILD_TYPE}}\${{env.EXECUTABLE_NAME}}.exe
